name: effect
author: "sJimin"
main: effect\effect
version: Alpha 1.0
api:
- 2.0.0
- 1.13.0
  
permissions:
 portionsign.command.allow:
  descript: "Portion Sign permission"
  default: true
  